# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 20:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_entrada_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='autor',
        ),
    ]
